version: '3.8'                              #specifies the version of the Docker Compose file

services:                                   #define the various containers that make up your application
    nginx:                                  #name the container and define it
        build:                              #to build a container with a dockerfile
            context: ./nginx                 #files directory to build container
            dockerfile: ./Dockerfile   #specifies de dockerfile
        ports:
            - "80:80"                       #host:container
