version: '3.8'                              #specifies the version of the Docker Compose file

services:                                   #define the various containers that make up your application
    nginx:                                  #name the container and define it
        container_name: nginx               #name the container, if not docker uses random namxe
        build: ./requirements/nginx         #to build a container with a dockerfile
        ports:
            - "443:443"                     #host:container
        networks:
            - inception
        depends_on:                         #expresa dependencias de inicio y apagado entre servicios.
            - wordpress
        restart: unless-stopped

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        ports:
            - "9000:9000"
        networks:
            - inception
        depends_on:
            - wordpress
        restart: unless-stopped

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        ports:
            - "3306:3306"
        networks:
            - inception
        depends_on:
            - mariadb
        restart: unless-stopped

networks:
    inception:
        driver: bridge


#depends_on

#Compose crea servicios en orden de dependencia. En el siguiente ejemplo, dby redisse crean antes de web.
#Compose elimina los servicios en orden de dependencia. En el siguiente ejemplo, webse elimina antes dby redis.
#Compose garantiza que los servicios de dependencia se hayan iniciado antes de iniciar un servicio dependiente. Compose espera a que los servicios de dependencia estén "listos" antes de iniciar un servicio dependiente.

#restart: Cuando se establece en true, Compose reinicia este servicio después de actualizar el servicio de dependencia. Esto se aplica a un reinicio explícito controlado por una operación de composición y excluye el reinicio automático por parte del tiempo de ejecución del contenedor después de que el contenedor muere.
