version: '3.8' #specifies the version of the Docker Compose file

services: #define the various containers that make up your application

    nginx:
        image: nginx/Dockerfile
        ports: 
            - "80:80"
    db:
        image: 
