version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - WP
    depends_on:
      - wordpress
    restart: unless-stopped
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    restart: unless-stopped

volumes:
  WP:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/adrgonza/data/wp
  DB:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/adrgonza/data/db

networks:
    inception:
        driver: bridge